"""empty message

Revision ID: 12d9d41ee276
Revises: 3396d615904a
Create Date: 2018-09-19 02:07:29.934686

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '12d9d41ee276'
down_revision = '3396d615904a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('_password', sa.String(length=50), nullable=False))
    op.drop_column('cms_user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('password', mysql.VARCHAR(length=50), nullable=False))
    op.drop_column('cms_user', '_password')
    # ### end Alembic commands ###
